### ISSUE TITLE
Create JAR file?

### ISSUE THREAD

**Issue by AvangionQ** [JohnnyBazooka89/StSModEnergizedSpire#1]
Is there a JAR file to download for this mod?

**Comment by JohnnyBazooka89** [comment]
If you want get the jar, you can compile the project yourself or you can subscribe to the mod on steam workshop: https://steamcommunity.com/sharedfiles/filedetails/?id=1639939942 and then jar will be downloaded automatically to the folder `C:\Program Files (x86)\Steam\steamapps\workshop\content\646570\1639939942` (path to steam may vary).

But to be honest you don't really need to care about the jar, to play the mod just subscribe to the mod on steam and run Slay the Spire with mods.

**Comment by AvangionQ** [comment]
I'm running Slay the Spire using ModTheSpire 3.6.3 ... which seems to require JAR files to play each mod ... that is, unless if I'm missing something important about how this is supposed to work ...

**Comment by JohnnyBazooka89** [comment]
[EnergizedSpireMod.zip](https://github.com/JohnnyBazooka89/StSModEnergizedSpire/files/2923449/EnergizedSpireMod.zip)
(you need to unzip this file)

**Comment by AvangionQ** [comment]
Please add that ZIP file over here ... https://github.com/JohnnyBazooka89/StSModEnergizedSpire/releases
