### ISSUE TITLE
Ideas for more relics

### ISSUE THREAD

**Issue by AvangionQ** [JohnnyBazooka89/StSModEnergizedSpire#2]
If you'd like some ideas for more relics, check this out ... https://www.reddit.com/r/slaythespire/comments/bo168w/relic_ideas_free_to_use/

**Comment by JohnnyBazooka89** [comment]
Thank you for letting me know about this topic on reddit. I like some of your ideas, especially Honey Pot and  Snecko Blood/Snecko Fangs.
