### ISSUE TITLE
Energized Die - Add description of rolled relic's effect

### ISSUE THREAD

**Issue by Clauvin** [JohnnyBazooka89/StSModEnergizedSpire#3]
Energized Die is an interesting Energy Boss Relic, but unless the player already knows/remembers all six relics, he can end making bad plays and have them blocked by the relic.

The problem is that the counter for that currently is... to check the Slay The Spire Wikia, or saving the game and checking the relic compendium. :/

Suggestions to fix this:

* Six tooltips, one for each effect rolled, and a description change with the rolling.
* The relic adds temporarily to the player the relic rolled. So, if you got Velvet Choker, the player gains a Velvet Choker for that combat only.

**Comment by JohnnyBazooka89** [comment]
Will do.

**Comment by JohnnyBazooka89** [comment]
Added tooltips in version 1.3.5. It's released on Steam Workshop.

**Comment by JohnnyBazooka89** [comment]
Btw sorry for updating this so late, I didn't notice this issue in github, most people use comment section in Steam Workshop.

**Comment by Clauvin** [comment]
I understand, and I'm happy since the issue is fixed! Time to go through Energized Die runs!
