### ISSUE TITLE
Block Reminder Conflict Frost Orbs Unstable Molecule

### ISSUE THREAD

**Issue by imakunee** [JohnnyBazooka89/StSModEnergizedSpire#4]
Unstable Molecules causing frost orbs to instantly time out. This is caused by some conflict with the mod Block Reminder.

ModTheSpire 3.19.1
BaseMod 5.32.0
StSLib 1.22.0
BlockReminder 1.2.0
EnergizedSpire 1.8.1

Thank you for your time and effort!

**Comment by JohnnyBazooka89** [comment]
@imakunee
Thanks for the report. It was fixed in version 1.8.2.
