### ISSUE TITLE
Huge House removed a bottled card (modded bottle relic)

### ISSUE THREAD

**Issue by thomase535** [JohnnyBazooka89/StSModEnergizedSpire#5]
Huge House was able to remove a card that was bottled by a modded relic, Blizzard In A Bottle (Bundle of Terra). This should not be possible, as removing a bottled card causes the game to crash (hence shop removes and event removes not working on bottled cards, even from modded bottles, iirc).

**Comment by JohnnyBazooka89** [comment]
Thanks for reporting the bug.

It was fixed in version 1.19.0.
